name: "get next tag"
description: "next tag basen on git history"

inputs:
  prefix:
    description: 'tag prefix'
    required: true
    default: 'v'

  versioning:
    description: 'version format: "semver", "single-number", or "calver"'
    required: true
    default: 'semver'

  force:
    description: 'force next version'
    required: false
    default: ''

  pre-release-suffix:
    description: 'suffix for pre-release version'
    required: false
    default: ''

  calver-format:
    description: 'calver format: "YYYY.MM.MICRO", "YY.MM.MICRO", "YYYY.0M.MICRO", or "YY.0M.MICRO"'
    required: false
    default: 'YYYY.MM.MICRO'

  level:
    description: 'incrementing level, possible values: "major", "minor", "patch", "premajor", "preminor", "prepatch", or "prerelease"'
    required: true
    default: 'patch'

outputs:
  current_tag:
    description: "current tag"
  next_tag:
    description: "next tag"
  next_version:
    description: "next version without prefix"

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: refresh-cw
  color: blue
