name: "get next tag"
description: "next tag based on git history"

inputs:
  prefix:
    description: 'tag prefix'
    required: true
    default: 'v'

  versioning:
    description: 'version format'
    required: true
    default: 'semver'

  force:
    description: 'force next version'
    required: false
    default: ''

  pre-release-suffix:
    description: 'suffix for pre-release version'
    required: false
    default: ''

  level:
    description: 'incrementing level, possible values: "major", "minor", "patch", "premajor", "preminor", "prepatch", or "prerelease"'
    required: true
    default: 'patch'

  push-new-tag:
    description: 'should the action create and push the generated tag'
    required: false
    default: 'false'

  retries:
    description: 'how many times should the action retry generating and pushing new tag'
    required: false
    default: '0'

outputs:
  current_tag:
    description: "current tag"
  next_tag:
    description: "next tag"
  next_version:
    description: "next version without prefix"

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: refresh-cw
  color: blue
